# this is enough for kubernetes to create a persistent volume claim, it will use the default storage class to create a persistent volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
